name: tasker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc_test: ^9.1.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  path: ^1.9.0
  sqflite: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
